import React from "react";
import Item from "./Item";
import "../App.css";

function Listado() {
  const bosses = [
    {
      nombre: "Bestia Clerigo",
      nombreOriginalJapones: "教区長",
      afiliacion: "Bestia",
      ubicacion: "Yharnam Central (Gran Puente)",
      salud: "3015",
      recompensa: "Insignia de cazador de espadas",
      ecosDeSangreObtenidos: "4000",
      defensaFisica: "102",
      defContundente: "123",
      defensaContraataque: "102",
      defensaFuego: "51",
      defensaRelampago: "169",
      defensaSangre: "102",
      defensaArcana: "169",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "El brazo grande",
      debilidad: "Daños de Fuego",
      fasesDurantePelea: "1 fase",
      imagen: "Cleric Beast",
      imagen2: "bloodborne2",
      imagen3: "ClericBeast",
      imagen4: "bloodborne",
    },
    {
      nombre: "Padre Gascoigne",
      nombreOriginalJapones: "ガスコイン神父",
      afiliacion: "Bestia",
      ubicacion: "Yharnam Central (Tumba de Odeon)",
      salud: "2031",
      recompensa: "Llave de la tumba de Odeon",
      ecosDeSangreObtenidos: "1800",
      defensaFisica: "95 - 126",
      defContundente: "95 - 126",
      defensaContraataque: "95 - 126",
      defensaFuego: "68 - 52",
      defensaRelampago: "126",
      defensaSangre: "95 - 126",
      defensaArcana: "80 - 168",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "Golpes Contundentes",
      debilidad: "Daños de Fuego",
      fasesDurantePelea: "2 fases",
      imagen: "FatherGascoigne",
      imagen2: "BeastGascoigne",
      imagen3: "Gascoigne",
      imagen4: "bloodborne",
    },
    {
      nombre: "Bestia Sedienta de Sangre",
      nombreOriginalJapones: "ガ血に渇いた獣",
      afiliacion: "Bestia",
      ubicacion: "Old Yharnam (Iglesia del buen Caliz)",
      salud: "3470",
      recompensa: "Llave de la tumba de Odeon",
      ecosDeSangreObtenidos: "6600",
      defensaFisica: "107",
      defContundente: "107",
      defensaContraataque: "107",
      defensaFuego: "59",
      defensaRelampago: "172",
      defensaSangre: "107",
      defensaArcana: "172",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "180",
      puntoDebil: "Golpes Contundentes",
      debilidad: "Daños de Fuego",
      fasesDurantePelea: "3 fases",
      imagen: "BestiaSedSangre",
      imagen2: "bloodborne2",
      imagen3: "BestiaSedSangre",
      imagen4: "bloodborne",
    },
    {
      nombre: "La bruja de Hemwick",
      nombreOriginalJapones: "ヘムウィックの魔女",
      afiliacion: "Unknown",
      ubicación: "Carril del cementerio de Hemwick",
      salud: "2611",
      recompensa: "Globo ocular inyectado",
      ecosDeSangreObtenidos: "11800",
      defensaFisica: "78",
      defContundent: "78",
      defensaContraataque: "78",
      defensaFuego: "82",
      defensaRelampago: "101",
      defensaSangre: "78",
      defensaArcana: "78",
      defensaVenenoLento: "200",
      defensaVenenoRapido: "180",
      puntoDebil: "Golpes Contundentes",
      debilidad: "Daño físico",
      fasesDurantePelea: "2 fases",
      imagen: "Witch of Hemwick",
      imagen2: "bloodborne2",
      imagen3: "HemwickWitch",
      imagen4: "bloodborne",
    },
    {
      nombre: "Darkbeast Paarl",
      nombreOriginalJapones: "黒獣パール - ローランの黒獣",
      afiliacion: "bestia",
      ubicacion: "Viejo Yharna (Cementerio de la Bestia Oscura)",
      salud: "4552",
      recompensa: "Insignia de cazador de chispa",
      ecosDeSangreObtenidos: "21000",
      defensaFisica: "120",
      defContundente: "144",
      defensaContraataque: "120",
      defensaFuego: "102",
      defensaRelampago: "360",
      defensaSangre: "120",
      defensaArcana: "90",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "Piernas delanteras",
      debilidad: "Daño arcano",
      fasesDurantePelea: "2 fases",
      imagen: "BestiaOscuraPaarl",
      imagen2: "bloodborne2",
      imagen3: "DarkBeastPaarl",
      imagen4: "bloodborne",
    },
    {
      nombre: "Vicaria Amelia",
      nombreOriginalJapones: "教区長エミーリア",
      afiliacion: "Bestia de la iglesia de la sanación",
      ubicacion: "Cathedral Ward",
      salud: "5367",
      recompensa: "Colgante de Oro",
      ecosDeSangreObtenidos: "15000",
      defensaFisica: "112",
      defContundente: "135",
      defensaContraataque: "112",
      defensaFuego: "61",
      defensaRelampago: "180",
      defensaSangre: "112",
      defensaArcana: "180",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "Cabeza",
      debilidad: "Daños de Fuego",
      fasesDurantePelea: "2 fases",
      imagen: "VicariaAmelia",
      imagen2: "bloodborne2",
      imagen3: "VicarAmelia",
      imagen4: "bloodborne",
    },
    {
      nombre: "Sombras de Yharnam",
      nombreOriginalJapones: "ヤーナムの影",
      afiliacion: "unknown",
      ubicacion: "Bosques Prohibidos",
      salud: "3645 - 2302 - 2046",
      recompensa: "Runa Extasis de sangre",
      ecosDeSangreObtenidos: "18600",
      defensaFisica: "89 - 89 - 89",
      defContundente: "89 - 89 - 89",
      defensaContraataque: "89 - 89 - 89",
      defensaFuego: "110 - 122 - 110",
      defensaRelampago: "83 - 83 - 196",
      defensaSangre: "89 - 89 - 89",
      defensaArcana: "73 - 73 - 196",
      defensaVenenoLento: "200 - 200 - 200",
      defensaVenenoRapido: "180 - 180 - 180",
      puntoDebil: "Golpes Contundentes",
      debilidad: "Varia por cada ente",
      fasesDurantePelea: "3 fases",
      imagen: "Shadow_of_Yharnam",
      imagen2: "bloodborne2",
      imagen3: "ShadowsYharnam",
      imagen4: "bloodborne",
    },
    {
      nombre: "Martir Logarius",
      nombreOriginalJapones: "殉教者ローゲリウス",
      afiliacion: "Verdugos de la iglesia de la sanación",
      ubicacion: "Castillo abandonado de Cainhurst",
      salud: "9081",
      recompensa: "corona de ilusiones",
      ecosDeSangreObtenidos: "25600",
      defensaFisica: "132",
      defContundente: "132",
      defensaContraataque: "132",
      defensaFuego: "212",
      defensaRelampago: "238",
      defensaSangre: "132",
      defensaArcana: "384",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "Golpes Contundentes",
      debilidad: "Daño físico",
      fasesDurantePelea: "2 fases",
      imagen: "MartyrLogarius",
      imagen2: "bloodborne2",
      imagen3: "Logarius",
      imagen4: "bloodborne",
    },
    {
      nombre: "Amygdala",
      nombreOriginalJapones: "アメンドーズ",
      afiliacion: "Los Grandes",
      ubicacion: "Frontera de Pesadilla (Cámara de Amygdala)",
      salud: "6404",
      recompensa: "Caliz de Loran Enfermo",
      ecosDeSangreObtenidos: "21000",
      defensaFisica: "127",
      defContundente: "153",
      defensaContraataque: "127",
      defensaFuego: "89",
      defensaRelampago: "89",
      defensaSangre: "127",
      defensaArcana: "89",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "Cabeza",
      debilidad: "Fuego, Rayo y Arcano",
      fasesDurantePelea: "1 fase",
      imagen: "Amygdala",
      imagen2: "bloodborne2",
      imagen3: "Amygdala2",
      imagen4: "bloodborne",
    },
    {
      nombre: "Rom, La araña vacua",
      nombreOriginalJapones: "白痴の蜘蛛",
      afiliacion: "Pariente Los grandes",
      ubicacion: "Byrgenwerth",
      salud: "5058",
      recompensa: "Cáliz Raíz de Pthumeru Inferior",
      ecosDeSangreObtenidos: "22600",
      defensaFisica: "130",
      defContundente: "130",
      defensaContraataque: "130",
      defensaFuego: "93",
      defensaRelampago: "58",
      defensaSangre: "130",
      defensaArcana: "104",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "laterales",
      debilidad: "Rayo",
      fasesDurantePelea: "2 fases",
      imagen: "Rom",
      imagen2: "bloodborne2",
      imagen3: "Rom2",
      imagen4: "bloodborne",
    },
    {
      nombre: "El renacido",
      nombreOriginalJapones: "再誕者",
      afiliacion: "Los grandes",
      ubicacion: "Yahar'gul la aldea invisible",
      salud: "10375",
      recompensa: "Columna vertebral amarilla x3",
      ecosDeSangreObtenidos: "33000",
      defensaFisica: "135",
      defContundente: "162",
      defensaContraataque: "135",
      defensaFuego: "94",
      defensaRelampago: "54",
      defensaSangre: "135",
      defensaArcana: "391",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "La cabeza",
      debilidad: "Daños de rayo",
      fasesDurantePelea: "1 fase",
      imagen: "Reborn",
      imagen2: "bloodborne2",
      imagen3: "OneReborn",
      imagen4: "bloodborne",
    },
    {
      nombre: "Ebrietas, hija del cosmos",
      nombreOriginalJapones: "星の娘エーブリエタース",
      afiliacion: "Pariente de los grandes",
      ubicacion: "Distrito superior de la catedral",
      salud: "12493",
      recompensa: "Gran Cáliz de Isz",
      ecosDeSangreObtenidos: "28800",
      defensaFisica: "252",
      defContundente: "336",
      defensaContraataque: "100",
      defensaFuego: "84",
      defensaRelampago: "64",
      defensaSangre: "168",
      defensaArcana: "238",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "La cabeza",
      debilidad: "Daños de rayo y fuego",
      fasesDurantePelea: "2 fase",
      imagen: "Ebrietas2",
      imagen2: "bloodborne2",
      imagen3: "Ebrietas",
      imagen4: "bloodborne",
    },
    {
      nombre: "Micolash Huesped de la pesadilla",
      nombreOriginalJapones: "悪夢の主ミコラーシュ",
      afiliacion: "Escuela de Mensis",
      ubicacion: "Pesadilla de Mensis",
      salud: "5250",
      recompensa: "Jaula de Mensis",
      ecosDeSangreObtenidos: "48800",
      defensaFisica: "169",
      defContundente: "134",
      defensaContraataque: "125",
      defensaFuego: "124",
      defensaRelampago: "125",
      defensaSangre: "179",
      defensaArcana: "232",
      defensaVenenoLento: "144",
      defensaVenenoRapido: "132",
      puntoDebil: "Golpes contundentes",
      debilidad: "Daño físico",
      fasesDurantePelea: "2 fase",
      imagen: "Micolash",
      imagen2: "bloodborne2",
      imagen3: "Micolash2",
      imagen4: "bloodborne",
    },
    {
      nombre: "Nodriza de Mergo",
      nombreOriginalJapones: "メルゴーの乳母",
      afiliacion: "Pariente de los grandes",
      ubicacion: "Pesadilla de Mensis",
      salud: "14081",
      recompensa: "Tercera parte de cordon umbilical",
      ecosDeSangreObtenidos: "72000",
      defensaFisica: "147",
      defContundente: "177",
      defensaContraataque: "147",
      defensaFuego: "110",
      defensaRelampago: "110",
      defensaSangre: "147",
      defensaArcana: "110",
      defensaVenenoLento: "250",
      defensaVenenoRapido: "180",
      puntoDebil: "Espalda",
      debilidad: "Daños de fuego y rayo",
      fasesDurantePelea: "2 fase",
      imagen: "WetNurse",
      imagen2: "bloodborne2",
      imagen3: "Mergo",
      imagen4: "bloodborne",
    },
    {
      nombre: "Gehrman, El primer cazador",
      nombreOriginalJapones: "最初の狩人ゲールマン",
      afiliacion: "Cazador",
      ubicacion: "El Sueño del cazador",
      salud: "14293",
      recompensa: "Insignia del viejo cazador",
      ecosDeSangreObtenidos: "128000",
      defensaFisica: "150",
      defContundente: "150",
      defensaContraataque: "150",
      defensaFuego: "105",
      defensaRelampago: "97",
      defensaSangre: "150",
      defensaArcana: "97",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "Golpes contundentes",
      debilidad: "Daños de fuego y arcano",
      fasesDurantePelea: "3 fase",
      imagen: "Gerhman",
      imagen2: "bloodborne2",
      imagen3: "Gehrman_multiple_big",
      imagen4: "bloodborne",
    },
    {
      nombre: "Presencia Lunar",
      nombreOriginalJapones: "月の魔物",
      afiliacion: "Los grandes",
      ubicacion: "El sueño del cazador",
      salud: "8909",
      recompensa: " - ",
      ecosDeSangreObtenidos: "230000",
      defensaFisica: "137",
      defContundente: "137",
      defensaContraataque: "137",
      defensaFuego: "114",
      defensaRelampago: "114",
      defensaSangre: "137",
      defensaArcana: "114",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "Cabeza",
      debilidad: "Daños de fuego, rayo y arcano",
      fasesDurantePelea: "1 fase",
      imagen: "Moon_Presence",
      imagen2: "bloodborne2",
      imagen3: "MoonPresence",
      imagen4: "bloodborne",
    },
    {
      nombre: "Ludwig, La espada sagrada",
      nombreOriginalJapones: "醜い獣、ルドウイーク",
      afiliacion: "Bestia de la iglesia de la sanación",
      ubicacion: "Pesadilla del cazador",
      salud: "16658",
      recompensa: "Espada de luz de Luna Sagrada",
      ecosDeSangreObtenidos: "34500",
      defensaFisica: "140",
      defContundente: "140",
      defensaContraataque: "140",
      defensaFuego: "119",
      defensaRelampago: "168",
      defensaSangre: "140",
      defensaArcana: "252",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "Cabeza",
      debilidad: "Daños de fuego",
      fasesDurantePelea: "2 fases",
      imagen: "Ludwig",
      imagen2: "bloodborne2",
      imagen3: "Ludwig_1",
      imagen4: "bloodborne",
    },
    {
      nombre: "Laurence, el primer vicario",
      nombreOriginalJapones: "初代教区長ローレンス",
      afiliacion: "Bestia de la iglesia de la sanación",
      ubicacion: "Gran Catedral de Pesadilla",
      salud: "21243",
      recompensa: "Abrazo de la bestia",
      ecosDeSangreObtenidos: "29500",
      defensaFisica: "148",
      defContundente: "178",
      defensaContraataque: "148",
      defensaFuego: "744",
      defensaRelampago: "200",
      defensaSangre: "148",
      defensaArcana: "200",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "180",
      puntoDebil: "Golpes Contundentes",
      debilidad: "Daños fisicos",
      fasesDurantePelea: "2 fases",
      imagen: "Laurence",
      imagen2: "bloodborne2",
      imagen3: "Laurence_1",
      imagen4: "bloodborne",
    },
    {
      nombre: "Lady Maria de la torre astral ",
      nombreOriginalJapones: "時計塔のマリア",
      afiliacion: "Los antiguos cazadores",
      ubicacion: "La torre Astral",
      salud: "14081",
      recompensa: "Dije Celestial",
      ecosDeSangreObtenidos: "39000",
      defensaFisica: "147",
      defContundente: "147",
      defensaContraataque: "147",
      defensaFuego: "177",
      defensaRelampago: "103",
      defensaSangre: "147",
      defensaArcana: "103",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "Golpes Vicerales",
      debilidad: "Daños de rayo y arcanos",
      fasesDurantePelea: "3 fases",
      imagen: "Maria",
      imagen2: "bloodborne2",
      imagen3: "LadyMaria",
      imagen4: "bloodborne",
    },
    {
      nombre: "Huerfano de Kos",
      nombreOriginalJapones: "ゴースの遺子",
      afiliacion: "Los grandes",
      ubicacion: "El pueblo costero",
      salud: "19216",
      recompensa: "Parasito de Kos",
      ecosDeSangreObtenidos: "60000",
      defensaFisica: "183",
      defContundente: "183",
      defensaContraataque: "183",
      defensaFuego: "205",
      defensaRelampago: "228",
      defensaSangre: "183",
      defensaArcana: "274",
      defensaVenenoLento: "999",
      defensaVenenoRapido: "999",
      puntoDebil: "Daño Contraataque",
      debilidad: "Daños de rayo",
      fasesDurantePelea: "2 fases",
      imagen: "OrphanofKos",
      imagen2: "bloodborne2",
      imagen3: "Ook",
      imagen4: "bloodborne",
    },
  ];

  return (
    <div className="imagen-L">
      <div className="App">
        <div className="contenedor-principal">
          <h2>Wiki personalizada de jefes de Bloodborne</h2>
          <div className="grid-container">
            {bosses.map((boss, index) => (
              <Item
                key={index}
                nombre={boss.nombre}
                nombreOriginalJapones={boss.nombreOriginalJapones}
                afiliacion={boss.afiliacion}
                ubicacion={boss.ubicacion}
                salud={boss.salud}
                recompensa={boss.recompensa}
                ecosDeSangreObtenidos={boss.ecosDeSangreObtenidos}
                defensaFisica={boss.defensaFisica}
                defContundente={boss.defContundente}
                defensaContraataque={boss.defensaContraataque}
                defensaFuego={boss.defensaFuego}
                defensaRelampago={boss.defensaRelampago}
                defensaSangre={boss.defensaSangre}
                defensaArcana={boss.defensaArcana}
                defensaVenenoLento={boss.defensaVenenoLento}
                defensaVenenoRapido={boss.defensaVenenoRapido}
                puntoDebil={boss.puntoDebil}
                debilidad={boss.debilidad}
                fasesDurantePelea={boss.fasesDurantePelea}
                imagen={boss.imagen}
                imagen2={boss.imagen2}
                imagen3={boss.imagen3}
                imagen4={boss.imagen4}
              />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Listado;
